version: '3.8'

services:
  app:
    build:
      context: .
    container_name: nest-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:root@localhost:5432/extraordinario"
    networks:
      - app-network
      

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: extraordinario
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


